### ISSUE TITLE
Race condition in the CI

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#268]
The CI has been red irregularly for a while now. A race condition is happening somewhere and it's bad. I've investigated a bit and some times I've seen this when starting vna.

    D, [2014-09-18T05:21:57.311205 #3583] DEBUG -- : 0x0000bbbbbbbbbbbb interface/simulated: adding ipv4 address to if-dhcp1/7 (02:00:00:00:01:01/10.0.0.2)
    D, [2014-09-18T05:21:57.312151 #3583] DEBUG -- : 0x0000bbbbbbbbbbbb interface/simulated: adding ipv4 address to if-router1/9 (02:00:00:00:01:02/10.0.0.1)
    D, [2014-09-18T05:21:57.445246 #3583] DEBUG -- : 0x0000bbbbbbbbbbbb interface/simulated: adding ipv4 address to if-dhcp2/8 (02:00:00:00:01:04/10.0.0.3)
    I, [2014-09-18T05:22:07.964501 #3583]  INFO -- : 0x0000bbbbbbbbbbbb datapath: cleaned up
    W, [2014-09-18T05:22:08.022376 #3583]  WARN -- : Terminating task: type=:call, meta={:method_name=>:run_normal}, status=:callwait
    E, [2014-09-18T05:22:08.023401 #3583] ERROR -- : Vnet::Openflow::Switch crashed!
    RuntimeError: can't add a new key into hash during iteration
            /home/centos/work/wakame-vnet/vnet/lib/vnet/core/port_manager.rb:33:in `[]='
            /home/centos/work/wakame-vnet/vnet/lib/vnet/core/port_manager.rb:33:in `insert'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
            /home/centos/work/wakame-vnet/vnet/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'

When looking at [the code at port_manager:33](https://github.com/axsh/openvnet/blob/master/vnet/lib/vnet/core/port_manager.rb#L33), it doesn't seem to be iterating so the iteration must be happening in another thread. This might be our race condition.

**Comment by Metallion** [comment]
Continued in these issues:

https://github.com/axsh/openvnet/issues/300

https://github.com/axsh/openvnet/issues/292
