### ISSUE TITLE
The vnet-webapi crash with early API call

### ISSUE THREAD

**Issue by master-q** [axsh/openvnet#269]
```
$ git clone git@github.com:wakameci/wakame-ci-cluster.git
$ cd wakame-ci-cluster/kvm-guests/192.168.3.10-vnetdev
$ ./replace.sh
$ telnet localhost 15310
10-vnetdev login: kemukins
Password: 
[kemukins@10-vnetdev ~]$ cat /opt/axsh/vnetscript/0000-runall.sh
#!/bin/bash
#
# requires:
#  bash
#
set -e
set -o pipefail

01-init-database.sh
02-start-vnmgr-webapi.sh
03-setup-openvnet.sh
04-start-vna.sh
05-start-lxc.sh
06-connect-tap-to-vswitch.sh
07-login-lxc1.sh
[kemukins@10-vnetdev ~]$ 0000-runall.sh      
db:create...
db:init...
vnet-vnmgr start/running, process 1358
vnet-webapi start/running, process 1361
vnet-vnmgr start/running, process 1358
vnet-webapi start/running, process 1361
/opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9090 (Errno::ECONNREFUSED)
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/axsh/openvnet/ruby/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/httparty-0.11.0/lib/httparty/request.rb:92:in `perform'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:461:in `perform_request'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:414:in `post'
	from /opt/axsh/openvnet/vnctl/lib/vnctl/cli/base.rb:35:in `block (3 levels) in <class:Base>'
	from /opt/axsh/openvnet/vnctl/lib/vnctl/cli/base.rb:89:in `block in define_add'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:109:in `invoke'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:232:in `block in subcommand'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/axsh/openvnet/ruby/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /opt/axsh/openvnet/vnctl/bin/vnctl:42:in `<main>'
[kemukins@10-vnetdev ~]$ 03-setup-openvnet.sh
[kemukins@10-vnetdev ~]$ 04-start-vna.sh 
[kemukins@10-vnetdev ~]$ 05-start-lxc.sh 
[kemukins@10-vnetdev ~]$ 06-connect-tap-to-vswitch.sh 
[kemukins@10-vnetdev ~]$ 07-login-lxc1.sh 
localhost login: root
Password: 
[root@localhost ~]# ifup eth0
[root@localhost ~]# ifconfig|head -3
eth0      Link encap:Ethernet  HWaddr 00:18:51:E5:35:01  
          inet addr:10.0.0.200  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::218:51ff:fee5:3501/64 Scope:Link
```

**Comment by Metallion** [comment]
This is not something needed to fix right now. The details are in https://github.com/axsh/openvnet/pull/290#issuecomment-99744148.
