### ISSUE TITLE
Registry port setting 

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#484]
```ruby
    class Registry < Fuguta::Configuration
      param :adapter, :default => "redis"
      param :host, :default => '127.0.0.1'
      param :port, :default => 6379
    end
```

Even when the 'port' is changed in the common.conf file it still uses the default port number.

**Comment by Metallion** [comment]
I tried to reproduce this just now and the bug didn't occur.

common.conf contents
```
registry {
  adapter "redis"
  host "127.0.0.1"
  #port 6379
  port 6380
}
```

vna.log contents
```
E, [2016-08-19T16:31:21.988064 #3836] ERROR -- : Actor crashed!
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6380 (Errno::ECONNREFUSED)
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:345:in `rescue in establish_connection'
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:331:in `establish_connection'
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:101:in `block in connect'
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:100:in `connect'
        /opt/axsh/openvnet/vnet/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:364:in `ensure_connected'
```

You can see that OpenVNet correctly tried to connect to the port specified in common.conf. Redis wasn't running there so it got a connection refused as expected.
